# Generated by Django 4.0.5 on 2022-06-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_instagram_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram_post',
            name='caption',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
