# Generated by Django 4.0.5 on 2022-06-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_instagram_post_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram_post',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
