# Generated by Django 4.0.5 on 2022-06-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_instagram_post_date_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram_post',
            name='profile_of_creator',
        ),
    ]
