# Generated by Django 4.0.5 on 2022-06-05 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_rename_author_user_likes_person_liking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_likes',
            name='likes',
            field=models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
