# Generated by Django 4.0.5 on 2022-06-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_likes_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagram_post',
            old_name='creator',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user_likes',
            name='likes',
        ),
        migrations.AlterField(
            model_name='user_likes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_count', to='app.instagram_post'),
        ),
    ]
