# Generated by Django 4.0.5 on 2022-06-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_creator_instagram_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram_post',
            name='profile_of_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
