# Generated by Django 4.0.5 on 2022-06-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_newsletterrecipients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletterrecipients',
            old_name='username',
            new_name='user',
        ),
    ]
