# Generated by Django 4.0.5 on 2022-06-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_username_newsletterrecipients_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram_post',
            name='profile_of_creator',
        ),
    ]
