# Generated by Django 4.0.5 on 2022-06-06 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_author_user_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_comment',
            name='commented_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
